version: '3'
services:
  dev:
    user: root
    volumes:
      - .:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock 
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    command: bash -c "while sleep 1000; do :; done"
 
