#!/bin/bash

command="${1:-all}"

# regardless of capitalisation, includes numbers 1-9, $ limits to the exact characters, not more
function isTrue() {
  if [[ "${@^^}" =~ ^(TRUE$|Y$|O$|ON$|[1-9]) ]]; then
    return 0;
  fi
  return 1
}

# if not empty and DEBUG=true is set
if [[ ! -z "$DEBUG" ]] && isTrue "$DEBUG"; then
  DEBUG=true make -f "$APP_DIR"/Makefile "$command"
else
  make -f "$APP_DIR"/Makefile "$command"
fi
