version: '3'
x-base-image: &default-base-image # name for reference
  env_file: go.env
  image: golang:${GO_VARIANT:-1.21.1-bookworm}
  working_dir: $DOCKER_GOSRC/webserver
  environment:
    - HOST=$HOST
    - SERVERPORT=${SERVERPORT:-8000}
  volumes:
    - $GOSRC:$DOCKER_GOSRC
  ports:
    - ${SERVERPORT:-8000}:${SERVERPORT:-8000}
    - 40000:40000
services:
  go-dev:
    << : *default-base-image
    container_name: go-dev
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    command: >       # rather command than entrypoint due to vscode container
      /bin/bash -c "
        go mod download &&
        go install &&
        bash
      "
  go-debug:
    <<: *default-base-image
    container_name: go-debug
    entrypoint: bash -c
    command:
      - |
          go install .
          go install github.com/go-delve/delve/cmd/dlv@latest
          dlv --listen=:40000 --headless=true --api-version=2 --accept-multiclient exec /go/bin/webserver
  go-server:
    << : *default-base-image
    container_name: go-server
    entrypoint: bash -c
    command:
      - |
        go install .
        webserver
  build-wasm:
    image: sebastianheil/wasm-builder:0.0.16
    environment:
      - CFD=backend/src/webserver/CFD.yaml
      - WWW=backend/src/webserver/frontend/public/static/js/CodeDistributor
      - PLUGINS=backend/src/codedistribution/plugins
      - FUNCTIONS=backend/src/webserver/frontend/public/static/js/CodeDistributor
    working_dir: /usr/app
    volumes:
      - .:/usr/app
    entrypoint: wasmbuilder
    command: all
